import java.io.*;
import java.util.Random;

/**
 * Replaces the piece set baked in the ROM with a random piece set. This requires a ROM that has already been patched
 * so that uses a fixed piece set instead of a pieces set that is randomly generated by the game itself.
 */
public class RandomizePieceSet {

    public static void main(String[] args) {
        if (args.length < 2) {
            System.out.println("Usage: RandomizePieceSet SOURCE_ROM DEST_ROM");
            System.exit(0);
        }

        Random random = new Random();

        try (BufferedInputStream inputStream = new BufferedInputStream(new FileInputStream(args[0]));
             BufferedOutputStream outputStream = new BufferedOutputStream(new FileOutputStream(args[1]))) {
            // Copy first part of ROM.
            for (int i = 0; i < 0x5710; i++) {
                outputStream.write(inputStream.read());
            }

            // Fill out piece spawn table with random pieces.
            for (int i = 0; i < 0x0400; i++) {
                inputStream.read();
                int piece = random.nextInt(7);
                outputStream.write(piece);
            }

            // Copy remainder of ROM.
            int originalByte;
            while ((originalByte = inputStream.read()) != -1) {
                outputStream.write(originalByte);
            }
        }
        catch (IOException e) {
            e.printStackTrace();
        }

    }

}
